#!/usr/bin/env python3
"""
List all journal entry types that have no matching rule, by year.

Used to: (1) add rules where possible (mutually exclusive), (2) document
unmatched types for accounting verification.

Usage (from veritas-accounting):
  python3 scripts/list_unmatched_types.py -i examples/journal_entry_2020_2024.xlsx \\
    -r 账目分类明细.xlsx -a 账目分类明细.xlsx -s 2020 -s 2021 -s 2022 -s 2024

Writes: docs/unmatched-types-for-verification.txt (and prints to stdout).
"""

import sys
from pathlib import Path
from collections import defaultdict

import click

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from veritas_accounting.excel.journal_reader import JournalEntryReader
from veritas_accounting.excel.rule_reader import MappingRuleReader
from veritas_accounting.models.account_loader import AccountHierarchyLoader
from veritas_accounting.transformation.journal_to_ledger import JournalToLedgerTransformer


def load_rules(rules_file: str, account_file: str | None):
    """Load rules; use journal_to_ledger when rules file equals account file."""
    reader = MappingRuleReader()
    path = Path(rules_file)
    use_jtl = (
        path.exists()
        and account_file
        and Path(account_file).resolve() == path.resolve()
    )
    if use_jtl:
        rules, _ = reader.read_rules_from_journal_to_ledger(rules_file)
        return rules
    rules, _ = reader.read_rules(rules_file)
    return rules


@click.command()
@click.option("--input", "-i", required=True, type=click.Path(exists=True), help="Journal Excel")
@click.option("--rules", "-r", type=click.Path(exists=True), help="Rules Excel (账目分类明细.xlsx)")
@click.option("--account-hierarchy", "-a", type=click.Path(exists=True), help="Account hierarchy Excel")
@click.option("--sheet", "-s", "sheets", multiple=True, default=["2020", "2021", "2022", "2024"],
              help="Sheet names to process")
@click.option("--output", "-o", type=click.Path(), default=None,
              help="Output file (default: docs/unmatched-types-for-verification.txt)")
def main(input: str, rules: str | None, account_hierarchy: str | None, sheets: tuple, output: str | None):
    if not rules or not account_hierarchy:
        raise click.UsageError("--rules and --account-hierarchy are required")
    base = Path(__file__).parent.parent
    out_path = Path(output) if output else base / "docs" / "unmatched-types-for-verification.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    click.echo("Loading rules and account hierarchy...")
    rules_list = load_rules(rules, account_hierarchy)
    loader = AccountHierarchyLoader()
    hierarchy = loader.load_from_excel(account_hierarchy, sheet_name="ledger_new")
    transformer = JournalToLedgerTransformer(rules_list, hierarchy)

    # (year, old_type) -> { count, entry_ids[] }
    by_type: dict[tuple[int, str], dict] = defaultdict(lambda: {"count": 0, "entry_ids": []})
    all_unmatched = []

    for sheet_name in sheets:
        try:
            year_int = int(sheet_name)
        except ValueError:
            year_int = 0
        reader = JournalEntryReader(sheet_name=sheet_name)
        entries, _ = reader.read_journal_entries(input)
        if not entries:
            click.echo(f"  {sheet_name}: no entries")
            continue
        _, unmatched = transformer.transform(entries)
        for e in unmatched:
            y = getattr(e, "year", None) or year_int
            t = (e.old_type or "").strip()
            if not t:
                t = "(blank)"
            key = (y, t)
            by_type[key]["count"] += 1
            if len(by_type[key]["entry_ids"]) < 20:
                by_type[key]["entry_ids"].append(e.entry_id or "")
            all_unmatched.append((y, t, e.entry_id, e.description, e.amount))

        click.echo(f"  {sheet_name}: {len(entries)} entries, {len(unmatched)} unmatched")

    # Sort by year, then type
    rows = []
    for (year, old_type), data in sorted(by_type.items()):
        ids = data["entry_ids"]
        sample = ", ".join(ids[:5]) + (" ..." if len(ids) > 5 else "")
        rows.append((year, old_type, data["count"], sample))
    total_unmatched = sum(r[2] for r in rows)

    lines = [
        "Unmatched journal types (no mapping rule)",
        "Generated by scripts/list_unmatched_types.py",
        "Use: add rules in 账目分类明细.xlsx (journal_to_ledger) or document for accounting verification.",
        "",
        "Year | Type | Count | Sample entry IDs",
        "-----|------|-------|------------------",
    ]
    for year, old_type, count, sample in rows:
        lines.append(f"{year} | {old_type!r} | {count} | {sample}")
    lines.extend(["", f"Total unmatched entries: {total_unmatched}", ""])
    text = "\n".join(lines)
    click.echo("\n" + text)
    out_path.write_text(text, encoding="utf-8")
    click.echo(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
